PiPorSeries: PiPorSeriesConMensajes.o Buzon.o
	g++ -g PiPorSeriesConMensajes.o Buzon.o -o PiPorSeries

PiPorSeriesConMensajes.o: PiPorSeriesConMensajes.cc 
	g++ -c -g PiPorSeriesConMensajes.cc

Buzon.o: Buzon.cc Buzon.h
	g++ -c -g Buzon.cc